### ISSUE TITLE
board size 

### ISSUE THREAD

**Issue by sMustafov** [tomw1808/blocktactoe#3]
https://github.com/tomw1808/blocktactoe/blob/c3d471a6e10574b6b6a71e31e5a60346bd0b9d8d/contracts/TicTacToe.sol#L11 here you can replace the number 3 with "boardSize" variable if you make it constant.

**Comment by tomw1808** [comment]
You can, but it won't give you any more benefits than making it a constant.

The intial idea of the whole course was to make it with a variable board-size. So someone can play tic tac toe on a 3x3 board, of if they "feel funky" they can increase the size to 100x100. The problem is that you can't define a storage variable to address[someVar][someOtherVar], so the whole plan was obsolete.
